### ISSUE TITLE
Looking for somebody to maintain this project

### ISSUE THREAD

**Issue by akurtovic** [akurtovic/InstaRaider#65]

**Comment by akurtovic** [comment]
I started this project more than two years ago because I simply needed a quick script to download all of my Instagram photos. Since then it's been cloned thousands of times and used for awesome stuff like quickly gathering lots of images to train machine learning algorithms and probably not-so-awesome stuff like downloading Instagram model pictures. I'm glad that people have found it useful and have forked InstaRaider and contributed over that time, however, I don't have the time or the interest in continuing to maintain this project. As with any web scrapping application, stuff is bound to change and break over time. I will still accept pull requests that fix any major issues, but if somebody else is interested in taking over this project please let me know.

**Comment by drydenp** [comment]
I did fix some things in that certain Instagram tags seem to be no longer present (particularly the PRIVATE stuff). I also needed to upgrade to a different "driver" for the web engine, the one included with Firefox doesn't really work, although apparently a fix was pushed very recently.

I'm not even sure if it IS included with firefox. Anyway. Selenium now works, for me. I have added a pull request to your repository, where you can take from what you want.

Regards.

**Comment by tobe81cwb** [comment]
I did a similar program, it is not really a fork because I made from scratch, just follow the same idea as you.
The difference that my program does not have any dependencies besides Python (no need of Selenium) and still not using the Instagram API.

https://github.com/tobe81cwb/instaripper

**Comment by tobe81cwb** [comment]
Just to update. I made a new version.
The lastest version has some dependencies now, but all Python packages, and still no need of Selenium, Firefox, etc.

Several new options has been added today, like:
- Download from private profiles (if you have permission)
- Add metadata to images (EXIF)
- Overwrite existing files
- Limit the number of posts to download
- Ignore video files
- Download from several profiles at once.
- Generate a HTML gallery

Last time I publish here! Sorry!

**Comment by akurtovic** [comment]
@tobe81cwb Sorry I'm just now responding. I'll have to check out your project and play with it a little. I was looking for somebody to take this repo over mostly because I don't have the time required to make updates and review pull requests. Your project seems like it already does what InstaRaider did and has additional features. If it makes sense, I'll just add a note that InstaRaider is no longer supported and add a link to your repo.

**Comment by tobe81cwb** [comment]
Currently, the project has some bugs, especially on large instagram accounts (that have more than 3k posts).

**Comment by drydenp** [comment]
Mostly also you need more iterations of the up/down scrolling and I suggest scrolling up a little before scrolling farther down. Especially this little thing in the beginning already changes a lot in how many pictures it downloads. Also you need to scroll often even before hitting e.g. 20 posts.

**Comment by drydenp** [comment]
Also I don't think it is a good Idea, Selenium has some dependencies of course but the project will work for longer as Facebook is going to install protection measures in the future that will disallow access unless your system can access javascript. Trust me. Don't throw this away please. They have already done so on Facebook long ago so Instagram is in the pipleline I am sure.

**Comment by tobe81cwb** [comment]
I really don't see any advantage on using Selenium. I'm simulating the ajax requests to the instagram server. Selenium will be a better option if the instagram interface and/or urls requests change frequently.

**Comment by drydenp** [comment]
I just told you. Everything that used Facebook AJAX calls before they changed the system is now utterly broken. The only thing that still works is stuff that used Selenium.

They have introduced an authorization measure where:
1) they can detect you are running a bot
2) they ask for a security token to be passed that is generated and loaded by javascript, and you have to authorize yourself using this (using an AJAX call) in order to continuing downloading data (sending requests for e.g. new bits of information).

Therefore I am pretty sure the javascript itself uses AJAX to obtain the information for the security challenge, and you would basically have to completely decode that process (e.g. using javascript debugging) to circumvent it. For Selenium it would be a breeze. Moreover with Selenium they probably wouldn't detect you are running a bot. I mean, I don't like it myself, direct AJAX calls are much cleaner, right?

I am just saying do not throw this thing away because it might prove to be more important later on.

That Facebook "security challenge" is not inherently secure, I think you can still get around it even by not doing anything fancy because they are still giving a lot of data in the pages they do send... but it is rare for a script to run without not encountering that chalenge and I do not really know how they do it yet (but I'm not the best of javascript hackers ;-)).

**Comment by drydenp** [comment]
For me I am just happy using a selenium solution because (a) I can see it works (visually) and (b) I run no risk of some faggot ass wannabe smartass from creating something that he/she will later abandon and will turn out to be utterly broken in the end as well ;-). Certainly if that means the current project is going to be defunct entirely.

I am sorry if you are not capable or able to process pull requests Akurtovic.

Myself I am not versed enough in this python thing (and Selenium as well) to manage something like this (and my life is usually in disarray to begin with). My apologies, to everyone ;-).

**Comment by tobe81cwb** [comment]
drydenp, I really understand why you prefer a selenium solution, but for me, this don't work.
I made my script because I wanna a daemon, or a script that I can run with cron, to download medias everyday, in a minimal linux system (without GUI), so, for me, selenium, firefox, etc it's not a option.

About "javascript debugging", "security challenge", and everything.. what are you talking about? I just seending 'referer header', 'sessions headers', and 'csrf tokens', and everything is working correctly.

Just downloaded 15548 medias from a instagram account now, twice in a row, and got only 2 incorrect downloads.
It's 13GB of downloads, take only 20 minutes (a connection of 200 Mbps) with 10 threads.

I can reorganize the code, and create "web drivers" to work with the requests packages or selenium package, but, for now, I don't see a real advantage doing this.

I'm not asking for development of InstaRaider to be stopped, I'm just offering an alternative. For me, the development of InstaRaider can continue if anyone is willing to do, and because who knows, I'm not the "some faggot ass wannabe smartass" you mentioned that it will stop development also at any time (if you look at the graphs, you'll see that I only update the project on the weekends in my spare time, and I might tire me that).

For me, my project it was just a way to play with Python. I don't care much for Instagram (I never used my account).

**Comment by drydenp** [comment]
Well I am sorry if I offended you ;-). But that was slightly on purpose. You take it very well though.

So my apologies in any case, I cannot write very well these days, so sometimes bad stuff comes out okay.

And I know, I just think you are promoting the thing as a replacement, or with the attitude that it is going to be better (because you post here). And I know you realize that. So.

I agree with what you say. My reason for having a Facebook thing was also a background thing, and not something you could do with or in a GUI.

What I am talking about is that Facebook owns Instagram and although to this day Instagram is not secured, it might very well be in the future, that is all I am saying.

I am also not asking for you to incorporate everything. I believe that if you would really have done Akurtovic a favour here, you would have introduced maybe some addon to his system, or taken over the project, I don't know. But a replacement just throws away the old and makes it seem like you want to be more important or for your product to be known as the superior one, you know.

So I am perfectly fine with your product, sure. There are python scripts that can do the same (or could do the same) on Facebook what you are doing today on Instagram. Very well made python scripts. But currently (I haven't checked back) I think they are defunct.

Facebook doesn't allow it anymore. The only ones who can still do it are the ones using Selenium, is all I am saying. I am not sure if it could not be done. I just don't know how to do it myself. And I don't have the time for it now. So although personally I *also* do not like requiring a GUI for my personal operations, in that sense of the word, that I wanted to do elsewhere on something else, you *can* create a virtual X server (client) that will do the same thing without ever requiring a display ;-). You will just have Firefox running in a virtual system not connected to any screen ;-).

Anyway, regards. I just think the limitations of these things is not being able to execute javascript, that's all. They could change their implementation every day and inject new parameters into it every day, and your python (or PHP) scripts would have to constantly deal with that. It's not really possible if they really want to go that far.

**Comment by drydenp** [comment]
Again, I do not mean to offend like that, I just don't know how to make things clear without using strong words sometimes, and it doesn't come out right at all most of the time ;-). Thank you for your efforts in any way, I think of course having background ability or projects is a good thing.

So please do not feel offended, but I am just slight or was just slightly offended by you promoting it as a complete replacement, and then the maintainer of this project thinking that will retire the current :p.

I think they are different things and I will just hope to keep using this one myself and If I ever do create a new version that works better I will try to create a pull request or otherwise maybe fork the project, I don't know. Regards.

**Comment by tobe81cwb** [comment]
Ok, let's see..

- "or with the attitude that it is going to be better (because you post here)"
I never said that my scripts was better, I said that don't have selenium and firefox dependencies... this don't make a program better or worse than other, just different...

- "But a replacement just throws away the old and makes it seem like you want to be more important or for your product to be known as the superior one"
Where I said that my script is a replacement or superior? I just saying that is a alternative! You can use the script that best suit you.
I made my script because I had certain needs that InstaRaider doesn't offer. Just like my scripts don't meet all your requirements.
Also, I don't read anything about that akurtovic will delete the repository, just he can't continue update the project. I believe that the repository will remain available to anyone who is willing to upgrade the project (create a fork, do a pull request, whatever). If not that, I'm sorry, but really didn't see that information.

- "you can create a virtual X server (client) that will do the same thing without ever requiring a display":
"minimal linux system"

- "but I am just slight or was just slightly offended by you promoting it as a complete replacement"
read the first answer. I never said that my script is a replacement, or is better, it's only different, with different requirements. see my original post:
"I did a similar program, it is not really a fork because I made from scratch, just follow the same idea as you. The difference that my program does not have any dependencies besides Python (no need of Selenium) and still not using the Instagram API." (no mention of be a complete replacement, superior or better)

- "I think they are different things and I will just hope to keep using this one myself and If I ever do create a new version that works better I will try to create a pull request or otherwise maybe fork the project, I don't know. Regards."
Yes, they are different things, my scripts it's only a alternative, that's all.
Again, I don't think akutorvic will delete this repository. But, just create a fork, and use it. 

you can continue to use strong words, I don't care, but do not jump to conclusions or worse, assert things about me that are not true.

**Comment by drydenp** [comment]
You moron. Just from the fact that you are posting here in this way makes it clear what your intentions are. They call that a "shameless plug". It's the same sort of thing as people posting on YouTube comment threads "please watch my vid".

You even alluded to that by saying "Last time I publish here! Sorry!". You are basically using a 'competitors' platform to promote your own product. Clearly not to add to the 'competitor', but as a way of saying "this and this is wrong with the competitor, but see what my product does!". That's what you're _doing_ no matter what you say your intentions are here. "I don't mean to destroy anything, but..." *goes and destroys something*. It's that same kind of thing.

The result of what you are doing here is that mr. Akurtovic is now intending to label your project the replacement for his project.

Boy, does that not sound like what you were trying to do all the time?

So you are like saying "It was not my intent" but it is still the result. If it is still the result, maybe that was your true intent here?

Akurtovic has already said : "If it makes sense, I'll just add a note that InstaRaider is no longer supported and add a link to your repo." but that is exactly the same of being an almost replacement here. It is like saying: "The next version is there". You even called your program or project "a new version" at one point even though you were alluding to your own program.

By itself "a new version" seems to imply a new version of this current project.

That threw me off a little I must admit. Apologies for that.

But you keep defending your project as being better, for instance by saying that you see no advantages of using Selenium. You are doing so within the context of this currrent project, thereby saying, in fact, that you see no advantages either for this current project to use Selenium.

Also, I never said that your use case was not important, and certainly not that it would not be important for you. But the users of this system may have different needs. Your peculiar and particular needs, that you allude to by saying "minimal Linux system" once more, do not reflect what most people need from it.

By posting here and arguing in this way, you ARE alluding to this idea that you think your project is a better match to what people need. If you don't want that, don't post it here, post it on your own platform, you know. You are like going to a competitors site and then saying "I think my project is better". But you don't have to say that verbatim, making references like "My program does this and that, but your program doesn't" silently implies the very same thing, and has the same results.

After all if you were not comparing or competing you would have been content to post it on your own space. At best, you could post a link here to your own thread or whatever, but you are posting a new project within the space of a question for a new maintainer. Maybe I did the same by posting a pull request here, but whatever.

It seemed the best place to start a discussion. And I definitely did not want to replace what he had.

But I think this is just shameless to begin with. And the result is the same: Akurtovic has already alluded to this idea that he considers your post and your project an answer to what he asked of people.

This also immediately has the result that new pull requests won't even be considered anymore and that means the same as considering this project "dead". So you've had your way and you've had your desired result.

Which means this project, in this case, linking to yours and alluding that it is the successor of some sort.

I really can't understand that you don't see what you're doing, but that's just me. It means you have now killed this project because mr. Akurtovic himself was already at wit's end, so to speak, in knowing what to do with it, and apparently, if I may be so bold, considers this the next best thing, so to speak.

Therefore, your project and your shameless submission here did in fact have a detrimental effect on this project to begin with, if it is already changing the wording of this project and its status.

So you don't even see what you're doing, but I cannot express it in any better way than this currently. My apologies. I just see a project dying when it didn't need to yet. "You bleed just to know you're alive" ;-), the song says. If your program is just for a minimalist Linux system and nothing else, then I see no reason why you'd want it to have anything of the status of an alternative to this current system. I know you say you don't want that, but it is still the result, and what is happening.

Maybe just look at the result of your actions, instead of what you said you wanted them to be, that's all I'm saying. I'm sorry, I'm outta here, bye.

**Comment by tobe81cwb** [comment]
Read only the first line! Ok...
I will delete my project! Tks! 

No comments anymore

**Comment by drydenp** [comment]
But just to recap, if someone says "Looking for someone to maintain this project" and you post into that thread saying "Look here, is my project!" than that is the answer to the question being asked, that you are giving here.

**Comment by drydenp** [comment]
Well if you are going to be this bitchy about it, I feel your project shouldn't even exist indeed.

Hypersensitive you might call that. I never told you to delete your project.

**Comment by tobe81cwb** [comment]
Deleted!
Never want to compete with anyone!
Like I said, my project it's just for fun with Python, but if I have to deal with people like you is not worth it!

**Comment by goatandsheep** [comment]
@drydenp what is going on? Is the repository being closed? Is there a new fork that will be maintained? There seems to have been something traumatic and I don't want to bring it back, but if it is to remain broken, it should be closed.

**Comment by drydenp** [comment]
@goatandsheep I do not have the capacity myself to maintain a project outside of me if it means having to supply patches and review patches; I do not even have sufficient Python skills for that currently.

Of course I can update my own fork which I will do and if it is going to be "just that fork" in that sense I won't mind hearing about it or requests or anything, I just cannot make a presence for it like this project is. I don't think I have pushed my latest changes; I believe I changed some of the loop code to ensure that all images would be taken in. Yes, pushed it now. So I don't mind writing code and creating patches, but I just cannot maintain it as a regular full scale (in that sense) "official" project. Currently there is a bug at least with the Gecko driver I am using (Marionette) in that the Window Resize doesn't work, but it is not actually required for proper functioning, (actually, Window Move) and other than that I have created a patch that would use a few more updated tags to find the state of the page.

This person whose words you cannot see here was advertising his counter-project that used direct API calls (Ajax, Json) to download pages without using any browser. I am fine with that but I just told him it was a different kind of project but he responded by defending his way of doing things and saying it was better. So he was posing it as a replacement even if he didn't want to admit to that and mr. Akurtovic here basically responded by calling it the replacement, well no small wonder, if no one else jumps in. Mr. Akurtovic wanted to close the repo or at least freeze it, call it unmaintained, and then direct people elsewhere. Well to me that just seems like a destructive way of doing things, after I became a little bit... mad that other person responded by saying he would _delete_his project -- not just remove it here, or accept that it could not be a replacement, even if it was an alternative -- but actually delete it for himself too. I think he must have misunderstood me a little bit ;(. I mean :( ;-).

I mean I myself am in favour of API-only calls but the reality is simply that such solutions stop working so I don't want this solution to disappear, that's all. I just mentioned how Facebook stopped such scripts from functioning on Facebook somewhere back in I don't know, maybe spring of 2015 or earlier. There have been "white hats" who created complete script suites (there is one on Github) fror Facebook friend graphs and whatnot but there have also been researchers who have done the same using Selenium, and I am sure their solution still works, but his doesn't, that's all.

So I am more than willing to receive requests or even patches on my form (perhaps not patches, I don't have the time or capacity to review code I do not know, and I don't know this code at all, no matter how little it can be). I mean fork. I just can't do any sort of taking over this project in full.

**Comment by drydenp** [comment]
So basically I don't know if Akurtovic is willing to merge changes into this while handing the writing of updates or the fixing of bugs to me, basically him staying the maintainer, but me creating the updates, I am fine with that. This is a small project to day and just a small script when it comes down to it. It does very simple things that I do not understand, but it does them well enough to be functional. Don't expect development on this any time soon but all the same just fixing bugs should be doable right.

Just check out the latest 3 commits on my fork (which are my commits). I have not rebased on upstream in the meantime but I am sure there have not been changes? The first commit creates the first changes to make it work with Marionette, the new gecko driver. Back in that day, the version from main had stopped working with the then-current Firefox. It may since have been fixed but Firefox seems to be moving towards that new driver anyway. I have not checked up on it in the meantime. There was a discussion somewhere, I a may find it again. The second commit is just a script to download 0.8 of the marionette driver. Also the commits mention "firefox nightly" which is not actually required so I can change that. (It is just a marionette thing, that they only support (or supported) nightly). I don't know much of all of it, just what I've found. The third commit fixes some loop code that didn't work quite as intended because they either looped too little (page refresh; ups and downs) or it didn't proceed down the page far enough to find (trigger) the latest download of images. After changing that code a little it started working (again) and I just left it at that. Basically to use that version you must install Firefox Nightly. I'll just add a commit to make it work with regular firefox if you want, I will do that now.

**Comment by drydenp** [comment]
I updated the thing to 0.9. Also I don't know how much sense this makes, it seems Amir was still integrating patches from other people. I mean, I can't do that. But at least for me, this version (my fork) works. That's all. See ya.

**Comment by goatandsheep** [comment]
Perhaps add some auto-testing through [Travis](https://travis-ci.org/)

**Comment by drydenp** [comment]
I'm really not going to turn this into a project more than it already was. The project is so simple, even if you wanted to test, you could just create a script that would download Insta profiles of various sizes. This is a script of less than 500 lines and that is even counting comments ;-). I'm sorry, but this is precisely the kind of thing I won't do, adding something like that if you are not familiar with it is a multi-hour process to begin with, and even then you might not want to be dependent on something like that.

Regards.

**Comment by distantstar** [comment]
To be honest, if there is one thing that could be changed, the download_video definition could use a bit of optimization adjustment. While iterating through all of the video is fine and I have no issues with it, if I have the videos already, cycling through all of the existing video is just a waste of processing time. I'm thinking about few tweaks here but haven't found a good way to do them yet. With that said though, I was/am hoping this project is still maintained. This tool have become invaluable for me as many people are using Instagram as their primary source of sharing pictures and short videos.

**Comment by wilkoklak** [comment]
Hey, I just wanted to tell you that in plain source, not the rendered one, there are og: meta tags. There is og:image for images + og:video if post contains video. I've just seen a post on your blog how you started this project and I don't know if you still use the display_src from bottom of rendered source, but if yes, then the thing I've mentioned might speed the program up a little bit.

**Comment by althonos** [comment]
Hi @akurtovic, considering you are not maintaining this project anymore, I wrote my own implementation called [althonos/instaLooter ](https://github.com/althonos/instaLooter) that works without the official API but also without Selenium, it should be easier to maintain. (I'm doing a bit of advert here)

**Comment by akurtovic** [comment]
@althonos Cool. I'll check it out and maybe put a link to your project in the README
